// lib/utils.js - Utility functions for the application

// Lists of adjectives and nouns to create readable workspace IDs
const adjectives = [
  'adorable',
  'adventurous',
  'amazing',
  'beautiful',
  'brave',
  'bright',
  'calm',
  'charming',
  'cheerful',
  'colorful',
  'cozy',
  'creative',
  'determined',
  'eager',
  'elegant',
  'energetic',
  'friendly',
  'gentle',
  'graceful',
  'happy',
  'harmonious',
  'intelligent',
  'jolly',
  'kind',
  'lively',
  'majestic',
  'mysterious',
  'nice',
  'peaceful',
  'pleasant',
  'powerful',
  'proud',
  'reliable',
  'splendid',
  'stunning',
  'thoughtful',
  'vibrant',
  'wonderful',
];

const nouns = [
  'ant',
  'bear',
  'bird',
  'butterfly',
  'cat',
  'chameleon',
  'deer',
  'dolphin',
  'eagle',
  'elephant',
  'fox',
  'giraffe',
  'horse',
  'jellyfish',
  'kangaroo',
  'koala',
  'lion',
  'monkey',
  'octopus',
  'owl',
  'panda',
  'penguin',
  'rabbit',
  'rhino',
  'squirrel',
  'tiger',
  'turtle',
  'whale',
  'wolf',
  'zebra',
];

/**
 * Generate a random ID for a new workspace
 * Format: adjective-adjective-noun (e.g., "happy-fuzzy-bear")
 * @returns {string} A random workspace ID
 */
function generateWorkspaceId() {
  const adjectives = [
    'happy',
    'sunny',
    'clever',
    'agile',
    'brave',
    'calm',
    'eager',
    'fancy',
    'gentle',
    'honest',
    'jolly',
    'kind',
    'lively',
    'merry',
    'nice',
    'polite',
    'proud',
    'quiet',
    'reliable',
    'silly',
    'talented',
    'witty',
    'zealous',
    'cool',
    'fancy',
    'amazing',
    'brilliant',
    'awesome',
    'fantastic',
    'wonderful',
  ];

  const nouns = [
    'apple',
    'banana',
    'cat',
    'dog',
    'elephant',
    'fox',
    'giraffe',
    'horse',
    'iguana',
    'jellyfish',
    'koala',
    'lion',
    'monkey',
    'newt',
    'octopus',
    'penguin',
    'quail',
    'rabbit',
    'snake',
    'tiger',
    'unicorn',
    'vulture',
    'whale',
    'xenops',
    'yak',
    'zebra',
    'bear',
    'dolphin',
    'eagle',
    'panda',
  ];

  const randomAdjective1 = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomAdjective2 = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];

  return `${randomAdjective1}-${randomAdjective2}-${randomNoun}`;
}

module.exports = {
  generateWorkspaceId,
};
